name: Docker Image CI

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]

env:
  RELEASE_VERSION: ${{  github.ref_name }}
  IMAGE_NAME: ymil/airflow-git 

jobs:
  login-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  

      - uses: actions/checkout@v2
      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:latest
        
      - name: Docker Push
       if: startsWith(github.ref, 'refs/tags/') # This condition ensures it's a tag push
        run: |
          docker push $IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$RELEASE_VERSION
          docker push $IMAGE_NAME:$RELEASE_VERSION